cluster.name: dc435
node.name: ${HOSTNAME}
network.host: 0.0.0.0
discovery.zen.ping.unicast.hosts:
  - master
node.master: false
node.data: false
node.ingest: false
node.ml: false
cluster.remote.connect: false
